export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_TYPES = 'GET_TYPES';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
export const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';
export const SORT_BY_ORDER = 'SORT_BY_ORDER';
export const GET_POKEMONS_BY_NAME = 'GET_POKEMONS_BY_NAME';
export const POST_POKEMON = 'POST_POKEMON';
